/**
 * Rule Recommendation Panel - Shows generated rules with syntax
 */

import React, { useState } from 'react';
import { Card, CardHeader, Button } from '../../../components';
import type { RuleRecommendation } from '../../../types/tickets';

interface RuleRecommendationPanelProps {
  recommendations: RuleRecommendation[];
}

export const RuleRecommendationPanel: React.FC<RuleRecommendationPanelProps> = ({ recommendations }) => {
  const [expandedId, setExpandedId] = useState<string | null>(recommendations[0]?.firewallId || null);

  const handleCopy = (syntax: string) => {
    navigator.clipboard.writeText(syntax);
  };

  return (
    <Card>
      <CardHeader
        title="Rule Recommendations"
        subtitle="Platform-specific firewall rules generated by AI"
      />

      <div className="space-y-3">
        {recommendations.map((rec) => {
          const isExpanded = expandedId === rec.firewallId;

          return (
            <div
              key={rec.firewallId}
              className="border border-slate-600 rounded-lg overflow-hidden"
            >
              {/* Header */}
              <button
                onClick={() => setExpandedId(isExpanded ? null : rec.firewallId)}
                className="w-full p-4 bg-slate-700/30 hover:bg-slate-700/50 transition-colors flex items-center justify-between"
              >
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                    rec.platform === 'aws' ? 'bg-orange-500/20' :
                    rec.platform === 'azure' ? 'bg-blue-500/20' :
                    rec.platform === 'gcp' ? 'bg-red-500/20' :
                    'bg-slate-500/20'
                  }`}>
                    <span className="text-lg">
                      {rec.platform === 'aws' ? '☁️' :
                       rec.platform === 'azure' ? '🔷' :
                       rec.platform === 'gcp' ? '🔶' :
                       '🖥️'}
                    </span>
                  </div>
                  <div className="text-left">
                    <h4 className="text-white font-semibold">{rec.firewallName}</h4>
                    <p className="text-sm text-slate-400">{rec.ruleType.replace(/_/g, ' ')}</p>
                  </div>
                </div>
                <svg
                  className={`w-5 h-5 text-slate-400 transition-transform ${isExpanded ? 'rotate-180' : ''}`}
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>
              </button>

              {/* Expanded Content */}
              {isExpanded && (
                <div className="p-4 bg-slate-800/50 space-y-3">
                  {/* Rule Summary */}
                  <div className="grid grid-cols-2 gap-3 text-sm">
                    <div className="p-2 bg-slate-700/30 rounded">
                      <span className="text-slate-400">Action:</span>{' '}
                      <span className={`font-semibold ${rec.rule.action === 'allow' ? 'text-emerald-400' : 'text-red-400'}`}>
                        {rec.rule.action.toUpperCase()}
                      </span>
                    </div>
                    <div className="p-2 bg-slate-700/30 rounded">
                      <span className="text-slate-400">Protocol:</span>{' '}
                      <span className="text-white font-mono">{rec.rule.protocol.toUpperCase()}</span>
                    </div>
                    <div className="p-2 bg-slate-700/30 rounded">
                      <span className="text-slate-400">Source:</span>{' '}
                      <span className="text-white font-mono text-xs">{rec.rule.source}</span>
                    </div>
                    <div className="p-2 bg-slate-700/30 rounded">
                      <span className="text-slate-400">Port:</span>{' '}
                      <span className="text-white font-mono">{rec.rule.port}</span>
                    </div>
                    <div className="col-span-2 p-2 bg-slate-700/30 rounded">
                      <span className="text-slate-400">Destination:</span>{' '}
                      <span className="text-white font-mono text-xs">{rec.rule.destination}</span>
                    </div>
                  </div>

                  {/* Rule Syntax */}
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <label className="text-sm font-medium text-slate-300">
                        Platform-Specific Syntax
                      </label>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleCopy(rec.syntax)}
                      >
                        <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                        </svg>
                        Copy
                      </Button>
                    </div>
                    <pre className="p-3 bg-slate-900 rounded-lg border border-slate-700 overflow-x-auto">
                      <code className="text-cyan-400 text-xs font-mono">{rec.syntax}</code>
                    </pre>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </Card>
  );
};
